
samples: tests/test_liqbio_sample.json

reference: tests/dummy_genome/dummy_genome.json

normal_bams: ["tests/dummy_normal/LB-P-NA12877-N-03098850-TD1-C31_nodups.bam", "tests/dummy_normal/LB-P-NA12877-N-03098850-TD1-C31_clipoverlap.bam"]

libdir: tests/libraries

umi: True

container: 
    base: False
    gridss: False
    franken: False

outdir: tests

steps: ALL

gnomAD: "/nfs/PROBIO/gnomad/r2.1/genomes/gnomad.genomes.r2.1.sites.noVEP.vcf.gz"

params:
    scratch: /tmp
    bwa:
        threads: 8
    bcftools:
        threads: 4
    samblaster:
        rm_dup: " --removeDups "
        threads: 8
    fastqc:
        threads: 1
    gatk3:
        threads: 1
        target_creator:
            java_options: "-Xmx4G -XX:ParallelGCThreads=4"
            extra: " -allowPotentiallyMisencodedQuals --maxIntervalSize 20000 "
            threads: 2
        indel_realigner:
            java_options: "-Xmx8G -XX:ParallelGCThreads=4"
            extra: " -allowPotentiallyMisencodedQuals --maxReadsForRealignment 5000000 --maxReadsInMemory 1000000 "
            wgs: " -allowPotentiallyMisencodedQuals --maxReadsForRealignment 7000 --maxReadsInMemory 1000000 "
            threads: 3
    picard:
        markdup:
            rmdups: "true"
            java_options: " -Xmx5g -XX:ParallelGCThreads=8 "
            extra: " "
            threads: 1
        merge_bam:
            java_options: " -Xmx10g "
        collectinsertsize:
            java_options: " -XX:ParallelGCThreads=8 "
            threads: 1
        collectoxog:
            java_options: " -XX:ParallelGCThreads=8  -Xmx2g"
            threads: 1
        collecthsmetrics:
            java_options: " -XX:ParallelGCThreads=8 "
            threads: 1
        collectwgsmetrics:
            java_options: " -XX:ParallelGCThreads=1 "
            threads: 1
    samtools:
        flagstat: 
            threads: 8
    fgbio:
        fastqtobam:
            java_options: " -Xmx10g -XX:+AggressiveOpts -XX:ParallelGCThreads=8 "
            threads: 1
        groupreadsbyumi:
            java_options: " -Xmx10g -XX:+AggressiveOpts -XX:ParallelGCThreads=8 "
            threads: 1
        callduplexconsensus:
            java_options: " -Xmx10g -XX:+AggressiveOpts -XX:ParallelGCThreads=8 "
            extra: " --min-reads 1 1 0 --min-input-base-quality 30 "
            threads: 4
        filterconsensus:
            java_options: " -Xmx10g -XX:+AggressiveOpts -XX:ParallelGCThreads=8 "
            error_rate: " --max-read-error-rate 1 --max-base-error-rate 0 "
            base_quality: " --min-base-quality 30 "
            extra: " --min-reads 1 1 0 --reverse-per-base-tags true --require-single-strand-agreement true  "
            threads: 1
        clipbam:
            java_options: " -Xmx10g -XX:+AggressiveOpts -XX:ParallelGCThreads=8 "
            extra: 
            threads: 1
    create_popvcf:
        threads: 1
    contest_cancer:
        min_genotype_ratio: 0.95
        threads: 1
    contam_caveat:
        threads: 1
    cnvkit:
        threads: 8
    cnvkit-fix:
        threads: 1
    cnstoseg:
        threads: 1
    cnv_tracks:
        threads: 1
    gatk4:
        threads: 1
        haplotypecaller:
            java_options: " -Xmx10g "
        mutect2:
            java_options: " -Xmx10g "
    strelka:
        threads: 8
    vardict:
        threads: 8
        min_alt_frac: 0.0002
        min_num_reads: null
    varscan:
        threads: 1
        java_options: " -Xmx10g "
        extra: " --min-coverage 3 --min-var-freq 0.0002 --p-value 0.05 --somatic-p-value 0.05 --strand-filter 0 "
    somaticseq:
        threads: 1
    svcaller:
        threads: 1
    svaba:
        threads: 8
    lumpy:
        threads: 8
    gridss:
        threads: 10
    gridss_filter:
        threads: 1
    purecn:
        threads: 1
        maxnonclonal: " --maxnonclonal 0.2 "
        minaf: " --minaf 0.01 "
    vcfaddsample:
        threads: 1
    liqbiocna:
        threads: 1
    vep:
        threads: 8
    msisensor:
        threads: 8
    multiqc:
        threads: 1
    sage:
        threads: 8
    jumble:
        threads: 1
