
samples: tests/test_liqbio_sample.json

reference: /home/sarath/GIT/autoseq-genome/autoseq-genome.json

params:
    scratch: /tmp/scratch
    bwa:
        threads:
    samblaster:
        rm_dup: true
        threads: 8
    gatk3:
        jarfile: scripts/GenomeAnalysisTK-3.5.jar
        realigner_target:
            java_options: "--Xmx8G -XX:ParallelGCThreads=10"
            extra: " -allowPotentiallyMisencodedQuals --maxIntervalSize 20000 "
            threads: 8
        indel_realigner:
            java_options:
            extra: 
            threads: 8
    picard:
        markdup:
            rmdups: "true"
            java_options: " -Xmx5g -XX:ParallelGCThreads=8 "
            extra:
            threads:

    
