site_name: Autoseq-Snakemake
site_url: ""
site_description: Autoseq documentation .
site_author: Clinseq Team

repo_url: https://github.com/ClinSeq/autoseq-snakemake
edit_uri: ""

nav :
  - Autoseq: index.md
  - Quick Start: quick_start.md
  - Launching Samples in Server: server_launch.md
  - Autoseq Pipelines: autoseq_pipeline.md
  - General Description: barcodes.md
  - Autoseq Scripts: scripts.md

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python

markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - admonition
    - def_list
    
