import os
import uuid 
import json


include: "../utils/utils.py"
include: "../utils/clinseq_barcodes.py"


def extract_bam(sample, libdir, umi = False):
    """
    """
    project = sample.split("-")[0]

    if project == "AL":
        sample_capture_str = compose_lib_capture_str(extract_unique_capture(sample))
        pattern = libdir + "/" + sample_capture_str + "*nodups.bam"
    
    if project in ["PB", "LB"]:
        pattern = libdir + "/" + sample + "*nodups.bam"
        umibam_pattern = libdir + "/" + sample + "*clipoverlap.bam"
    
    if umi:
        umi_bam  = glob.glob(umibam_pattern)
        if len(umi_bam) == 1:
            return umi_bam[0]
        else:
            raise ValueError("Invalid UMI bam search: " + sample)

    nodups_bam = glob.glob(pattern)
    if len(nodups_bam) == 1:
        return nodups_bam[0]
    else:
        raise ValueError(" ".join(["Invalid bam : ", sample, nodups_bam]))


samples = json.load(open(config['samples']))
params = config['params']
refjson = json.load(open(config['reference']))

# loading reference files
basepath = os.path.dirname(config['reference'])
reference = make_paths_absolute(refjson, basepath)
umi = config['umi']
libdir = config['libdir']
outdir = config['outdir']

all_clinseq_barcodes = []
for sample_type in ['N', 'T', 'CFDNA']:
    for clinseq_barcode in sampledata[sample_type]:
        if clinseq_barcode_is_valid(clinseq_barcode):
            all_clinseq_barcodes.append(clinseq_barcode)
        else:
            raise ValueError("Invalid clinseq barcode: " + clinseq_barcode)

shell.prefix("set -eo pipefail;")

### Generate Capture Strings and Barcodes
NORMAL_CAPTURE = [extract_unique_capture(sample) 
                    for sample in all_clinseq_barcodes 
                        if '-N-' in sample][0]
CANCER_CAPTURE = [extract_unique_capture(sample) 
                    for sample in all_clinseq_barcodes 
                        if '-CFDNA-' in sample or '-T-' in sample][0]

cancer_sample  =  [for sample in all_clinseq_barcodes 
                        if '-CFDNA-' in sample or '-T-' in sample][0]
normal_sample  =  [for sample in all_clinseq_barcodes 
                        if '-N-' in sample][0]
NORMAL_CAPTURE_STR = compose_lib_capture_str(NORMAL_CAPTURE)
CANCER_CAPTURE_STR = compose_lib_capture_str(CANCER_CAPTURE)
NORMAL_SAMPLE_STR = compose_sample_str(NORMAL_CAPTURE)
CANCER_SAMPLE_STR = compose_sample_str(CANCER_CAPTURE)

### Extract bam files for downstream process

capture_to_results = collections.defaultdict(SinglePanelResults)
BAM_FILES = list()
capture_to_results[NORMAL_CAPTURE].bamfile = extract_bamfiles(normal_sample, libdir) 
capture_to_results[CANCER_CAPTURE].bamfile = extract_bamfiles(cancer_sample, libdir) 
BAM_FILES.append(capture_to_results[NORMAL_CAPTURE].bamfile)
BAM_FILES.append(capture_to_results[CANCER_CAPTURE].bamfile)

if umi:
    NORMAL_UMIBAM = extract_bamfiles(normal_sample, libdir, umi) 
    CANCER_UMIBAM = extract_bamfiles(normal_sample, libdir, umi) 
    BAM_FILES.append(NORMAL_UMIBAM)
    BAM_FILES.append(CANCER_UMIBAM)

for bam in BAM_FILES:
    bname = os.path.basename(bam)
    dstdir = os.path.join(outdir, "bams")

    if not os.path.exists(dstdir):
        os.makedirs(dstdir, exist_ok=True)
    
    if not os.path.exists(os.path.join(dstdir, bname)):
        os.symlink(os.path.join(bam), os.path.join(dstdir, bname))


samples_capture_str = [compose_lib_capture_str(unique_capture) 
                            for unique_capture in [NORMAL_CAPTURE, CANCER_CAPTURE]]



clinseq_barcodes = [sample_capture_str if CANCER_CAPTURE.project == "AL" else all_clinseq_barcodes]

###### QC workflow OUTPUTS
OUTPUT = list()

PICARD_QC = list()
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-insertsize.txt", 
                        sample=clinseq_barcodes))
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-oxog.txt",
                        sample=clinseq_barcodes))
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-hsmetrics.txt",
                        sample=clinseq_barcodes))

CONTEST = list()
CONTEST.append(outdir + "/contamination/pop_vcf_{}-{}.vcf".format(NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
CONTEST.append("{}/contamination/{}.contest.txt".format(outdir, CANCER_CAPTURE_STR))
CONTEST.append("{}/qc/{}-contam-qc-call.json".format(outdir, CANCER_CAPTURE_STR))

MSI = list()
MSI.append("{}/msisensor-{}-{}.tsv".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
QC_overview = "{}/qc/{}.qc_overview.pdf".format(outdir, "_".join(samples_capture_str))

OUTPUT.append(PICARD_QC)
OUTPUT.append(QC_overview)
OUTPUT.append(MSI)


###### CNV workflow OUTPUTS

# CNV_OUTPUT = list()
# CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.cns", sample=all_clinseq_barcodes))
# CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.cnr", sample=all_clinseq_barcodes))
# CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_profile.bedGraph", sample=all_clinseq_barcodes))
# CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_segments.bedGraph", sample=all_clinseq_barcodes))
# CNV_OUTPUT.append("{}/variants/{}-{}-liqbio-cna.json".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
# CNV_OUTPUT.append("{}/qc/{}-{}-liqbio-purity.json".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
# CNV_OUTPUT.append("{}/qc/{}-{}-liqbio-cna.png".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
# CNV_OUTPUT.append("{}/qc/{}-{}-frankenplot.html".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
#OUTPUT.append(CNV_OUTPUT)





wildcard_constraints:
    sdid = samples['sdid'],
    sample = "|".join(clinseq_barcodes),
    events = "|".join(["DEL", "DUP", "INV", "TRA"]),


rule all:
    input: 
        OUTPUT
    output:
        outdir + "/analysis_finished"
    shell:
        "date +'%Y-%m-%d T%T %:z' > {output}"



include: "rules/qc.smk"
# include: "rules/cnvcalling.smk"
# include: "rules/germline.smk"
# include: "rules/somatic.smk"
# include: "rules/structuralvariants.smk"
# include: "rules/vep.smk"