import os
import uuid
import glob 
import json


include: "../utils/utils.py"
include: "../utils/clinseq_barcodes.py"


samples = json.load(open(config['samples']))
params = config['params']
refjson = json.load(open(config['reference']))

# loading reference files
basepath = os.path.dirname(config['reference'])
reference = make_paths_absolute(refjson, basepath)
umi = config['umi']
libdir = config['libdir']
outdir = config['outdir']

all_clinseq_barcodes = []
for sample_type in ['N', 'T', 'CFDNA']:
    for clinseq_barcode in samples[sample_type]:
        if clinseq_barcode_is_valid(clinseq_barcode):
            all_clinseq_barcodes.append(clinseq_barcode)
        else:
            raise ValueError("Invalid clinseq barcode: " + clinseq_barcode)

shell.prefix("set -eo pipefail;")

### Generate Capture Strings and Barcodes
NORMAL_CAPTURE = [extract_unique_capture(sample) 
                    for sample in all_clinseq_barcodes 
                        if '-N-' in sample][0]
CANCER_CAPTURE = [extract_unique_capture(sample) 
                    for sample in all_clinseq_barcodes 
                        if '-CFDNA-' in sample or '-T-' in sample][0]

cancer_sample  =  [sample for sample in all_clinseq_barcodes 
                            if '-CFDNA-' in sample or '-T-' in sample][0]
normal_sample  =  [sample for sample in all_clinseq_barcodes 
                            if '-N-' in sample][0]
NORMAL_CAPTURE_STR = compose_lib_capture_str(NORMAL_CAPTURE)
CANCER_CAPTURE_STR = compose_lib_capture_str(CANCER_CAPTURE)
NORMAL_SAMPLE_STR = compose_sample_str(NORMAL_CAPTURE)
CANCER_SAMPLE_STR = compose_sample_str(CANCER_CAPTURE)

### Extract bam files for downstream process

capture_to_results = collections.defaultdict(SinglePanelResults)
BAM_FILES = list()
NORMAL_BAM, NORMAL_BAI = extract_bam(normal_sample, libdir)
CANCER_BAM, CANCER_BAI = extract_bam(cancer_sample, libdir)
capture_to_results[NORMAL_CAPTURE].bamfile = NORMAL_BAM
capture_to_results[CANCER_CAPTURE].bamfile = CANCER_BAM
BAM_FILES.extend([NORMAL_BAM, NORMAL_BAI])
BAM_FILES.extend([CANCER_BAM, CANCER_BAI])


if umi:
    NORMAL_UMIBAM, NORMAL_UMIBAI = extract_bam(normal_sample, libdir, umi) 
    CANCER_UMIBAM, CANCER_UMIBAI = extract_bam(cancer_sample, libdir, umi) 
    capture_to_results[NORMAL_CAPTURE].umibam = NORMAL_UMIBAM
    capture_to_results[CANCER_CAPTURE].umibam = CANCER_UMIBAM
    BAM_FILES.extend([NORMAL_UMIBAM, NORMAL_UMIBAI])
    BAM_FILES.extend([CANCER_UMIBAM, CANCER_UMIBAI])

for bam in BAM_FILES:
    bname = os.path.basename(bam)
    dstdir = os.path.join(outdir, "bams")

    if not os.path.exists(dstdir):
        os.makedirs(dstdir, exist_ok=True)
    
    if not os.path.exists(os.path.join(dstdir, bname)):
        os.symlink(os.path.join(bam), os.path.join(dstdir, bname))


samples_capture_str = [compose_lib_capture_str(unique_capture) 
                            for unique_capture in [NORMAL_CAPTURE, CANCER_CAPTURE]]

clinseq_barcodes = samples_capture_str if CANCER_CAPTURE.project == "AL" else all_clinseq_barcodes
capture_name = get_capture_name(CANCER_CAPTURE.capture_kit_id)
targets = reference['targets'][capture_name]['targets-bed-slopped20']

###### QC workflow OUTPUTS
OUTPUT = list()

PICARD_QC = list()
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-insertsize.txt", 
                        sample=clinseq_barcodes))
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-oxog.txt",
                        sample=clinseq_barcodes))
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-hsmetrics.txt",
                        sample=clinseq_barcodes))

CONTEST = list()
CONTEST.append(outdir + "/contamination/pop_vcf_{}-{}.vcf".format(NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
CONTEST.append("{}/contamination/{}.contest.txt".format(outdir, CANCER_CAPTURE_STR))
CONTEST.append("{}/qc/{}-contam-qc-call.json".format(outdir, CANCER_CAPTURE_STR))

MSI = list()
MSI.append("{}/msisensor-{}-{}.tsv".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
QC_overview = "{}/qc/{}.qc_overview.pdf".format(outdir, "_".join(samples_capture_str))

OUTPUT.append(PICARD_QC)
OUTPUT.append(QC_overview)
OUTPUT.append(MSI)


###### CNV workflow OUTPUTS

CNV_OUTPUT = list()
CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.cns", sample=clinseq_barcodes))
CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.cnr", sample=clinseq_barcodes))
CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_ann.cns", sample=clinseq_barcodes))
CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_profile.bedGraph", sample=clinseq_barcodes))
CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_segments.bedGraph", sample=clinseq_barcodes))
CNV_OUTPUT.append("{}/variants/{}-{}-liqbio-cna.json".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
CNV_OUTPUT.append("{}/qc/{}-{}-liqbio-purity.json".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
CNV_OUTPUT.append("{}/qc/{}-{}-liqbio-cna.png".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
CNV_OUTPUT.append("{}/qc/{}-{}-frankenplot.html".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
OUTPUT.append(CNV_OUTPUT)

for sample in clinseq_barcodes:
    # cnv results to sample capture 
    if '-N-' in sample:
        capture_to_results[NORMAL_CAPTURE].cns = outdir + "/cnv/{}.cns".format(sample)
        capture_to_results[NORMAL_CAPTURE].cnr = outdir + "/cnv/{}.cnr".format(sample)
        capture_to_results[NORMAL_CAPTURE].seg = outdir + "/cnv/{}_dnacopy.seg".format(sample)
    
    if '-CFDNA-' in sample or '-T-' in sample:
        capture_to_results[CANCER_CAPTURE].cns = outdir + "/cnv/{}.cns".format(sample)
        capture_to_results[CANCER_CAPTURE].cnr = outdir + "/cnv/{}.cnr".format(sample)
        capture_to_results[CANCER_CAPTURE].seg = outdir + "/cnv/{}_dnacopy.seg".format(sample)

    # svs results to sample capture
    for event in ["DEL", "DUP", "INV", "TRA"]:
        if '-N-' in sample:
            capture_to_results[NORMAL_CAPTURE].svs[event] = "{}/svs/svcaller/{}-{}.gtf".format(outdir, sample, event)
        
        if '-CFDNA-' in sample or '-T-' in sample:
            capture_to_results[CANCER_CAPTURE].svs[event] = "{}/svs/svcaller/{}-{}.gtf".format(outdir, sample, event)

VARIANTS = list()
VARIANTS.append("{}/variants/{}-all.germline.vep.vcf".format(outdir, NORMAL_CAPTURE_STR))
VARIANTS.append("{}/variants/{}-{}-all.somatic.vep.vcf".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR))
VARIANTS.append(expand(outdir + "/svs/svcaller/{sample}-{events}.gtf", sample=clinseq_barcodes, events=["DEL", "DUP", "INV", "TRA"]))
VARIANTS.append(expand(outdir + "/svs/svcaller/{sample}_effects.json", sample=clinseq_barcodes))
VARIANTS.append(expand(outdir + "/svs/{sample}-svs.bam", sample=clinseq_barcodes))
VARIANTS.append(expand(outdir + "/svs/{sample}-svs.gtf", sample=clinseq_barcodes))
VARIANTS.append("{}/svs/igv/{}-{}-sv-annotated.txt".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))

IGV = list()
IGV.append("{}/{}-{}-igvnav-input.txt".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR))
IGV.append("{}/{}-igvnav-input.txt".format(outdir, NORMAL_CAPTURE_STR))
IGV.append("{}/variants/{}-and-{}.germline-variants-somatic-afs.bedGraph".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
OUTPUT.append(VARIANTS)
OUTPUT.append(IGV)



wildcard_constraints:
    sdid = samples['sdid'],
    sample = "|".join(clinseq_barcodes),
    events = "|".join(["DEL", "DUP", "INV", "TRA"]),

container: config['container']['base']

containers = config['container']

rule all:
    input: 
        OUTPUT,
        directory("{}/multiqc".format(outdir)),
        directory(outdir + "/IGVsnapshots/somatic/"),
        "{}/IGVnav/igv_session_sv.xml".format(outdir),
        "{}/IGVnav/igv_session_snps.xml".format(outdir),
        directory(outdir + "/IGVsnapshots/svs/")
    output:
        outdir + "/analysis_finished"
    shell:
        "date +'%Y-%m-%d T%T %:z' > {output}"


rule generate_symlinks:
    input:
        OUTPUT
    output:
        "{}/IGVnav/igv_session_sv.xml".format(outdir),
        "{}/IGVnav/igv_session_snps.xml".format(outdir)
    params:
        outdir = outdir,
        target_bed = targets
    log:
        "{}/logs/generate_symlinks.log".format(outdir)
    shell:
        "generate_symlinks.py --targets {params.target_bed} --outdir {params.outdir}  2> {log} "


rule generate_IGVSnapshots_snv:
    input:
        xml = "{}/IGVnav/igv_session_snps.xml".format(outdir),
        somatic_snvs = "{}/{}-{}-igvnav-input.txt".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR),
        germline_snvs = "{}/{}-igvnav-input.txt".format(outdir, NORMAL_CAPTURE_STR)
    output:
        somatic_snvs = directory(outdir + "/IGVsnapshots/somatic/"),
        germline_snvs = directory(outdir + "/IGVsnapshots/germline/")
    params:
        vartype = "snv"
    container: containers['igv']
    threads: 8
    log:
        "{}/logs/generate_igvsnapshots_snvs.log".format(outdir)
    shell:
        "generate_igvsnapshots.py --xml {input.xml} "
        " --preferences $IGV_PREFS -t {params.vartype} "
        " --input  {input.somatic_snvs} "
        " --output {output.somatic_snvs} 2> {log}  && "
        "generate_igvsnapshots.py --xml {input.xml} "
        " --preferences $IGV_PREFS -t {params.vartype} "
        " --input  {input.germline_snvs} "
        " --output {output.germline_snvs}  2>> {log} "


rule generate_IGVSnapshots_sv:
    input:
        xml = "{}/IGVnav/igv_session_sv.xml".format(outdir),
        svs = "{}/svs/igv/{}-{}-sv-annotated.txt".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR),
    output:
        directory(outdir + "/IGVsnapshots/svs/")
    params:
        vartype = "sv"
    container: containers['igv']
    threads: 8
    log:
        "{}/logs/generate_igvsnapshots_svs.log".format(outdir)
    shell:
        """
        generate_igvsnapshots.py --xml {input.xml} \
            --preferences $IGV_PREFS -t {params.vartype}  \
            --input  {input.svs} \
            --output {output} 2> {log} 
        """

include: "rules/qc.smk"
include: "rules/cnvcalling.smk"
include: "rules/germline.smk"
include: "rules/somatic.smk"
include: "rules/vep.smk"
include: "rules/structuralvariants.smk"


