import os
import uuid 
import json


include: "../utils/utils.py"
include: "../utils/clinseq_barcodes.py"


samples = json.load(open(config['samples']))
params = config['params']
refjson = json.load(open(config['reference']))

# loading reference files
basepath = os.path.dirname(config['reference'])
reference = make_paths_absolute(refjson, basepath)
umi = config['umi']
libdir = config['libdir']
outdir = config['outdir']

shell.prefix("set -eo pipefail;")

### Generate Capture Strings
NORMAL_CAPTURE = [extract_unique_capture(sample) 
                    for sample in all_clinseq_barcodes 
                        if '-N-' in sample][0]
CANCER_CAPTURE = [extract_unique_capture(sample) 
                    for sample in all_clinseq_barcodes 
                        if '-CFDNA-' in sample or '-T-' in sample][0]

NORMAL_CAPTURE_STR = compose_lib_capture_str(NORMAL_CAPTURE)
CANCER_CAPTURE_STR = compose_lib_capture_str(CANCER_CAPTURE)
NORMAL_SAMPLE_STR = compose_sample_str(NORMAL_CAPTURE)
CANCER_SAMPLE_STR = compose_sample_str(CANCER_CAPTURE)

# create symlink for normal bam files
bams = config['bams']

pattern = bamdir + NORMAL_CAPTURE_STR + "*[nodups|clipoverlap].bam"



for bam in bams:
    bname = os.path.basename(bam)
    dstdir = os.path.join(outdir, "bams")

    if not os.path.exists(dstdir):
        os.makedirs(dstdir, exist_ok=True)
    
    if not os.path.exists(os.path.join(dstdir, bname)):
        os.symlink(os.path.join(bam), os.path.join(dstdir, bname))














include: "rules/qc.smk"
include: "rules/cnvcalling.smk"
include: "rules/germline.smk"
include: "rules/somatic.smk"
include: "rules/structuralvariants.smk"
include: "rules/vep.smk"