import os
import uuid
import json
import collections

include: "../utils/utils.py"
include: "../utils/clinseq_barcodes.py"

shell.prefix("set -eo pipefail;")

# Reading parameters
samples = json.load(open(config['samples']))
params = config['params']
refjson = json.load(open(config['reference']))

# loading reference files
basepath = os.path.dirname(config['reference'])
reference = make_paths_absolute(refjson, basepath)
umi = config['umi']
libdir = config['libdir']
steps = config['steps']
outdir = config['outdir']

# Need to check clinseq_barcodes and data available for those valid barcodes
sampledata, all_clinseq_barcodes = check_sampledata(libdir, samples)


# NORMAL, CANCER SAMPLES
for sample in all_clinseq_barcodes:
    if '-N-' in sample:
        NORMAL_CAPTURE = extract_unique_capture(sample)
    
    if '-CFDNA-' in sample or '-T-' in sample:
        CANCER_CAPTURE = extract_unique_capture(sample)

NORMAL_CAPTURE_STR = compose_lib_capture_str(NORMAL_CAPTURE)
CANCER_CAPTURE_STR = compose_lib_capture_str(CANCER_CAPTURE)
NORMAL_SAMPLE_STR = compose_sample_str(NORMAL_CAPTURE)
CANCER_SAMPLE_STR = compose_sample_str(CANCER_CAPTURE)

# Extract chromosome from target capture bed
capture_p2 = get_capture_name(CANCER_CAPTURE.capture_kit_id)
capture_s2 = get_capture_name("S2")

targets_p2 = reference['small-design'][capture_p2]['targets-bed']
p2_chromo = list(get_chromosomes(targets_p2))
targets_s2 = reference['small-design'][capture_s2]['targets-bed']
s2_chromo = list(get_chromosomes(targets_s2))


capture_to_results = collections.defaultdict(SinglePanelResults)
OUTPUT = list()

# 1. Preprocessing and Alignment 
BAM_FILES = expand(outdir + "/bams/{sample}_nodups.bam", sample=all_clinseq_barcodes)
UMIBAM_FILES = expand(outdir + "/bams/{sample}_clipoverlap.bam", sample=all_clinseq_barcodes)
OUTPUT.append(BAM_FILES)
OUTPUT.append(UMIBAM_FILES)

capture_to_results[NORMAL_CAPTURE].bamfile = get_capture_bam(NORMAL_CAPTURE, BAM_FILES)
capture_to_results[CANCER_CAPTURE].bamfile = get_capture_bam(CANCER_CAPTURE, BAM_FILES)
capture_to_results[NORMAL_CAPTURE].umibam = get_capture_bam(NORMAL_CAPTURE, UMIBAM_FILES)
capture_to_results[CANCER_CAPTURE].umibam = get_capture_bam(CANCER_CAPTURE, UMIBAM_FILES)

# 2. QC

FASTQC = expand(outdir + "/qc/fastqc/{sample}/", sample=all_clinseq_barcodes)
# OUTPUT.append(FASTQC)

PICARD_QC = list()
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-insertsize.txt", 
                        sample=all_clinseq_barcodes))
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-oxog.txt",
                        sample=all_clinseq_barcodes))
PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-hsmetrics.txt",
                        sample=all_clinseq_barcodes))

VARIANTS = list()
VARIANTS.append("{}/variants/{}-all.germline.vep.vcf".format(outdir, NORMAL_CAPTURE_STR))
VARIANTS.append("{}/variants/{}-{}-all.somatic.vep.vcf".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR))
VARIANTS.append(expand(outdir + "/svs/{sample}-{events}.gtf", sample=all_clinseq_barcodes, events=["DEL", "DUP", "INV", "TRA"]))
VARIANTS.append(expand(outdir + "/svs/{sample}_effects.json", sample=all_clinseq_barcodes))
VARIANTS.append("{}/svs/svaba/{}-{}.svaba.somatic.annotated.sv.vcf".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
VARIANTS.append("{}/svs/svaba/{}-{}.svaba.germline.annotated.sv.vcf".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
VARIANTS.append("{}/svs/lumpy/{}-{}-lumpy.vcf".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
VARIANTS.append("{}/svs/igv/{}-{}-sv-annotated.txt".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))

IGV = list()
IGV.append("{}/{}-{}-igvnav-input.txt".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR))
IGV.append("{}/{}-igvnav-input.txt".format(outdir, NORMAL_CAPTURE_STR))
IGV.append("{}/variants/{}-and-{}.germline-variants-somatic-afs.bedGraph".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))

# OUTPUT.append(VARIANTS)
# OUTPUT.append(IGV)


wildcard_constraints:
    sdid = samples['sdid'],
    sample = "|".join(all_clinseq_barcodes),
    events = "|".join(["DEL", "DUP", "INV", "TRA"]),
    p2_chr = "|".join(p2_chromo),
    s2_chr = "|".join(s2_chromo)


rule all:
    input: 
        OUTPUT,
        outdir + "/bams/intermediate_bamfiles.removed"
    output:
        outdir + "/analysis_finished"
    shell:
        "date +'%Y-%m-%d T%T %:z' > {output}"

include: "rules/split_targets.smk"
include: "../autoseq/rules/pre_processing.smk"
if umi:
    include: "rules/umi_processing.smk"
else:
    include: "../autoseq/rules/alignment.smk"

# include: "../autoseq/rules/qc.smk"
# include: "../autoseq/rules/structuralvariants.smk" 