import json
import collections


include: "../utils/utils.py"
include: "../utils/clinseq_barcodes.py"

samples = json.load(open(config['samples']))
params = config['params']
refjson = json.load(open(config['reference']))

# loading reference files
basepath = os.path.dirname(config['reference'])
reference = make_paths_absolute(refjson, basepath)
umi = config['umi']
libdir = config['libdir']
steps = config['steps']

# Need to check clinseq_barcodes and data available for those valid barcodes
sampledata, all_clinseq_barcodes = check_sampledata(libdir, samples)

outdir = config['outdir']

shell.prefix("set -eo pipefail;")

# NORMAL, CANCER SAMPLES
NORMAL_CAPTURE = [extract_unique_capture(sample) for sample in all_clinseq_barcodes if '-N-' in sample][0]
CANCER_CAPTURE = [extract_unique_capture(sample) for sample in all_clinseq_barcodes if '-CFDNA-' in sample or '-T-' in sample][0]
NORMAL_CAPTURE_STR = compose_lib_capture_str(NORMAL_CAPTURE)
CANCER_CAPTURE_STR = compose_lib_capture_str(CANCER_CAPTURE)
NORMAL_SAMPLE_STR = compose_sample_str(NORMAL_CAPTURE)
CANCER_SAMPLE_STR = compose_sample_str(CANCER_CAPTURE)

# Extract chromosome from target capture bed
capture_name = get_capture_name(CANCER_CAPTURE.capture_kit_id)
targets = reference['targets'][capture_name]['targets-bed-slopped20']
all_chromosomes = list(get_chromosomes(targets))

capture_to_results = collections.defaultdict(SinglePanelResults)
OUTPUT = list()

if 'ALL' in steps or 'preprocess' in steps:
    BAM_FILES = expand(outdir + "/bams/{sample}_nodups.bam", sample=all_clinseq_barcodes)
    UMIBAM_FILES = expand(outdir + "/bams/{sample}_clipoverlap.bam", sample=all_clinseq_barcodes)
    OUTPUT.append(BAM_FILES)
    if umi:
        OUTPUT.append(UMIBAM_FILES)

    capture_to_results[NORMAL_CAPTURE].bamfile = get_capture_bam(NORMAL_CAPTURE, BAM_FILES)
    capture_to_results[CANCER_CAPTURE].bamfile = get_capture_bam(CANCER_CAPTURE, BAM_FILES)
    capture_to_results[NORMAL_CAPTURE].umibam = get_capture_bam(NORMAL_CAPTURE, UMIBAM_FILES)
    capture_to_results[CANCER_CAPTURE].umibam = get_capture_bam(CANCER_CAPTURE, UMIBAM_FILES)

# QC outputs
samples_of_interest = [compose_lib_capture_str(unique_capture) 
                            for unique_capture in [NORMAL_CAPTURE, CANCER_CAPTURE]]

if 'ALL' in steps or 'qc' in steps:
    FASTQC = expand(outdir + "/qc/fastqc/{sample}/", sample=all_clinseq_barcodes)
    OUTPUT.append(FASTQC)

    PICARD_QC = list()
    PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-insertsize.txt", 
                            sample=all_clinseq_barcodes))
    PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-oxog.txt",
                            sample=all_clinseq_barcodes))
    PICARD_QC.append(expand(outdir + "/qc/picard/{sample}.picard-hsmetrics.txt",
                            sample=all_clinseq_barcodes))

    CONTEST = list()
    CONTEST.append(outdir + "/contamination/pop_vcf_{}-{}.vcf".format(NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    CONTEST.append("{}/contamination/{}.contest.txt".format(outdir, CANCER_CAPTURE_STR))
    CONTEST.append("{}/qc/{}-contam-qc-call.json".format(outdir, CANCER_CAPTURE_STR))
    
    MSI = list()
    MSI.append("{}/msisensor-{}-{}.tsv".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    QC_overview = "{}/qc/{}.qc_overview.pdf".format(outdir, "_".join(samples_of_interest))
    
    OUTPUT.append(QC_overview)
    OUTPUT.append(MSI)


if 'ALL' in steps or 'variants' in steps:
    CNV_OUTPUT = list()
    CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.cns", sample=all_clinseq_barcodes))
    CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.cnr", sample=all_clinseq_barcodes))
    # CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}.seg", sample=all_clinseq_barcodes))
    CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_ann.cns", sample=all_clinseq_barcodes))
    CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_profile.bedGraph", sample=all_clinseq_barcodes))
    CNV_OUTPUT.append(expand(outdir + "/cnv/{sample}_segments.bedGraph", sample=all_clinseq_barcodes))
    CNV_OUTPUT.append("{}/variants/{}-{}-liqbio-cna.json".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    CNV_OUTPUT.append("{}/qc/{}-{}-liqbio-purity.json".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    CNV_OUTPUT.append("{}/qc/{}-{}-liqbio-cna.png".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    CNV_OUTPUT.append("{}/qc/{}-{}-frankenplot.html".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    OUTPUT.append(CNV_OUTPUT)

# set results to capture
for sample in all_clinseq_barcodes:
    # cnv results to sample capture 
    if '-N-' in sample:
        capture_to_results[NORMAL_CAPTURE].cns = outdir + "/cnv/{}.cns".format(sample)
        capture_to_results[NORMAL_CAPTURE].cnr = outdir + "/cnv/{}.cnr".format(sample)
        capture_to_results[NORMAL_CAPTURE].seg = outdir + "/cnv/{}_dnacopy.seg".format(sample)
    
    if '-CFDNA-' in sample or '-T-' in sample:
        capture_to_results[CANCER_CAPTURE].cns = outdir + "/cnv/{}.cns".format(sample)
        capture_to_results[CANCER_CAPTURE].cnr = outdir + "/cnv/{}.cnr".format(sample)
        capture_to_results[CANCER_CAPTURE].seg = outdir + "/cnv/{}_dnacopy.seg".format(sample)

    # svs results to sample capture
    for event in ["DEL", "DUP", "INV", "TRA"]:
        if '-N-' in sample:
            capture_to_results[NORMAL_CAPTURE].svs[event] = "{}/svs/svcaller/{}-{}.gtf".format(outdir, sample, event)
        
        if '-CFDNA-' in sample or '-T-' in sample:
            capture_to_results[CANCER_CAPTURE].svs[event] = "{}/svs/svcaller/{}-{}.gtf".format(outdir, sample, event)


if 'ALL' in steps or 'variants' in steps:
    VARIANTS = list()
    VARIANTS.append("{}/variants/{}-all.germline.vep.vcf".format(outdir, NORMAL_CAPTURE_STR))
    VARIANTS.append("{}/variants/{}-{}-all.somatic.vep.vcf".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR))
    VARIANTS.append(expand(outdir + "/svs/svcaller/{sample}-{events}.gtf", sample=all_clinseq_barcodes, events=["DEL", "DUP", "INV", "TRA"]))
    VARIANTS.append(expand(outdir + "/svs/svcaller/{sample}_effects.json", sample=all_clinseq_barcodes))
    VARIANTS.append(expand(outdir + "/svs/{sample}-svs.bam", sample=all_clinseq_barcodes))
    VARIANTS.append(expand(outdir + "/svs/{sample}-svs.gtf", sample=all_clinseq_barcodes))
    VARIANTS.append("{}/svs/gridss/{}-gridss.evidence.bam".format(outdir, CANCER_CAPTURE_STR))
    VARIANTS.append("{}/svs/gridss/{}-gridss.evidence.bam".format(outdir, NORMAL_CAPTURE_STR))
    VARIANTS.append("{}/svs/igv/{}-{}-sv-annotated.txt".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))

    IGV = list()
    IGV.append("{}/{}-{}-igvnav-input.txt".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR))
    IGV.append("{}/{}-igvnav-input.txt".format(outdir, NORMAL_CAPTURE_STR))
    IGV.append("{}/variants/{}-and-{}.germline-variants-somatic-afs.bedGraph".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR))
    OUTPUT.append(VARIANTS)
    OUTPUT.append(IGV)


wildcard_constraints:
    sdid = samples['sdid'],
    sample = "|".join(all_clinseq_barcodes),
    events = "|".join(["DEL", "DUP", "INV", "TRA"]),
    chr = "|".join(all_chromosomes)

container: config['container']['base']

containers = config['container']
                                    

rule generate_symlinks:
    input:
        OUTPUT
    output:
        "{}/IGVnav/igv_session_sv.xml".format(outdir),
        "{}/IGVnav/igv_session_snps.xml".format(outdir)
    params:
        outdir = outdir,
        target_bed = targets
    log:
        "{}/logs/generate_symlinks.log".format(outdir)
    shell:
        "generate_symlinks.py --targets {params.target_bed} --outdir {params.outdir}  2> {log} " 


rule generate_IGVSnapshots_snv:
    input:
        xml = "{}/IGVnav/igv_session_snps.xml".format(outdir),
        somatic_snvs = "{}/{}-{}-igvnav-input.txt".format(outdir, CANCER_CAPTURE_STR, NORMAL_CAPTURE_STR),
        germline_snvs = "{}/{}-igvnav-input.txt".format(outdir, NORMAL_CAPTURE_STR)
    output:
        somatic_snvs = directory(outdir + "/IGVsnapshots/somatic/"),
        germline_snvs = directory(outdir + "/IGVsnapshots/germline/")
    params:
        vartype = "snv"
    container: containers['igv']
    threads: 8
    log:
        "{}/logs/generate_igvsnapshots_snvs.log".format(outdir)
    shell:
        "generate_igvsnapshots.py --xml {input.xml} "
        " --preferences $IGV_PREFS -t {params.vartype} "
        " --input  {input.somatic_snvs} "
        " --output {output.somatic_snvs} 2> {log}  && "
        "generate_igvsnapshots.py --xml {input.xml} "
        " --preferences $IGV_PREFS -t {params.vartype} "
        " --input  {input.germline_snvs} "
        " --output {output.germline_snvs}  2>> {log} "


rule generate_IGVSnapshots_sv:
    input:
        xml = "{}/IGVnav/igv_session_sv.xml".format(outdir),
        svs = "{}/svs/igv/{}-{}-sv-annotated.txt".format(outdir, NORMAL_CAPTURE_STR, CANCER_CAPTURE_STR),
    output:
        directory(outdir + "/IGVsnapshots/svs/")
    params:
        vartype = "sv"
    container: containers['igv']
    threads: 8
    log:
        "{}/logs/generate_igvsnapshots_svs.log".format(outdir)
    shell:
        """
        generate_igvsnapshots.py --xml {input.xml} \
            --preferences $IGV_PREFS -t {params.vartype}  \
            --input  {input.svs} \
            --output {output} 2> {log} 
        """


include: "rules/pre_processing.smk"
if umi:
    include: "rules/split_targets.smk"
    include: "rules/umi_processing.smk"
else:
    include: "rules/alignment.smk"
include: "rules/qc.smk"
include: "rules/cnvcalling.smk"
include: "rules/germline.smk"
include: "rules/somatic.smk"
include: "rules/structuralvariants.smk"
include: "rules/vep.smk"
include: "rules/dypd.smk"



rule all:
    input: 
        OUTPUT,
        outdir + "/bams/intermediate_bamfiles.removed",
        directory("{}/multiqc".format(outdir)),
        directory(outdir + "/IGVsnapshots/somatic/"),
        directory(outdir + "/IGVsnapshots/germline/"),
        directory(outdir + "/IGVsnapshots/svs/"),
        "{}/IGVnav/igv_session_sv.xml".format(outdir),
        "{}/IGVnav/igv_session_snps.xml".format(outdir),
        outdir + "/variants/{sample}.dypd.typeDPYD.csv"
    output:
        outdir + "/analysis_finished"
    params:
        sdid = samples["sdid"],
        project_id = config['project_id'],
        capture_id = "_".join(tumor_barcode + normal_barcode)
    run:
        try:
            response = update_sample_info(
                project_id=params.project_id,
                sdid=params.sdid,
                capture=params.capture_id,
                status=1 
            )

            if response.get("status") == "error":
                print(response.get("message", "Failed to update sample info."))

        except Exception as e:
            print(f"Error updating sample info: {e}")
        
        shell("date +'%Y-%m-%d T%T %:z' > {output}")